### ISSUE TITLE
invalid boolnull

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/bipf#8] opened 2021-02-19 19:35 UTC
Did a query where I just got the following error:

```
Uncaught Error: invalid boolnull
    at decode_boolnull (bundle-ui.js:43553)
    at decode_type (bundle-ui.js:43630)
    at decode_object (bundle-ui.js:43536)
    at decode_type (bundle-ui.js:43629)
    at Object.decode (bundle-ui.js:43642)
    at bundle-ui.js:102787
    at bundle-ui.js:148005
    at getData (bundle-ui.js:25400)
    at bundle-ui.js:25411
    at getBlock (bundle-ui.js:25380)
```

It came up as part of an ssb-db2 query I ran.  Not sure how to track it down, but it happened in response to this query:

```
SSB.db.query(SSB.db.operators.type("channel"), SSB.db.operators.toCallback((err, msgs) => { console.log("Error: ", err); console.log("Messages: ", msgs) }))
```

**Comment by arj03** [comment] 2021-03-09 08:30
Have you been able to reproduce this after you did the multiple tabs thing in browser?

**Comment by KyleMaas** [comment] 2021-03-10 23:16
Sorry for the delayed response - been a little busy. Because of that busyness, I haven't been active enough with ssb-browser-demo to really know if this is fixed yet.

**Comment by arj03** [comment] 2021-11-14 18:32
I'll close this because I think it was because of the concurrency and so not really a bug in this library.

**Closed by arj03** 2021-11-14 18:32 UTC
